AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    AWS Serverless Application

    Sample SAM Template for AWS Serverless Application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 9


Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: hello_world/
            Handler: app.lambda_handler
            Runtime: python3.6
            Tracing: Active
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /hello
                        Method: get

    GodbyWorldFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: hello_world/
        Handler: app.lambda_handler2
        Runtime: python3.6
        Tracing: Active
        Policies:
          - SQSSendMessagePolicy:
              QueueName: !GetAtt MySqsQueue.QueueName
        Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
          Variables:
            qname: !Ref MySqsQueue
        Events:
          GoodbyWorld:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /goodby
              Method: get

    MySQSQueueFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: hello_world/
        Handler: app.lambda_handler3
        Runtime: python3.6
        Tracing: Active
        Policies:
          - SNSPublishMessagePolicy:
              TopicName: !GetAtt ExampleTopic.TopicName
        Environment:
          Variables:
            topic: !Ref ExampleTopic
        Events:
          MySQSEvent:
            Type: SQS
            Properties:
              Queue: !GetAtt MySqsQueue.Arn
              BatchSize: 10

    MySNSFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: hello_world/
        Handler: app.lambda_handler4
        Runtime: python3.6
        Tracing: Active
        Environment:
          Variables:
            topic: 33
        Events:
          SNSEvent:
            Type: SNS
            Properties:
              Topic:
                Ref: ExampleTopic

    DynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        ProvisionedThroughput:
          WriteCapacityUnits: 5
          ReadCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - KeyType: HASH
            AttributeName: id

    MySqsQueue:
      Type: AWS::SQS::Queue

    ExampleTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: 'ExampleTopic'